[server]
headless = false  # Ensure this is set to false
enableCORS = false
enableXsrfProtection = false
port = 8501 # Add this line

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
